from enum import Enum

from tonos_ts4 import ts4


class DeAuctionTokenType(Enum):
    TIP3 = ts4.Cell(
        'te6ccgEBAgEASQABQ4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABABAEOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQ'
    )  # todo
    ECC = ts4.Cell('te6ccgEBAQEAKAAASxYPpw2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQ')  # todo
